services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - calc-network


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - calc-network

networks:
  calc-network:
    driver: bridge